import { Montserrat } from "next/font/google";
import "./css/globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${montserrat.variable} antialiased bg-black relative  overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
