import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope} h-full antialiased`}
    >
      <body className="min-h-full relative flex flex-col">{children}</body>
    </html>
  );
}
